<% attachments_root = Pathname(ENV['WORKDIR'].to_s.empty? ? Rails.root : ENV['WORKDIR']).join('motor-admin-attachments') %>

local:
  service: Disk
  root: <%= attachments_root %>

test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>

disk:
  service: Disk
  root: <%= attachments_root %>

aws_s3:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] %>
  bucket: <%= ENV['S3_ATTACHMENTS_BUCKET'] %>

google:
  service: GCS
  credentials: <%= JSON.parse(ENV['GCS_CREDENTIALS'] || '{}') %>
  project: <%= ENV['GCS_PROJECT'] %>
  bucket: <%= ENV['GCS_BUCKET'] %>
